# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            
tagline:          'Roberto Giovanni Ramírez Chavarrí'
description:      ''
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'RGRCH'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://github.com/poole/hyde
